# Generated by Django 4.1.5 on 2023-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=32, verbose_name='Название')),
                ('about_game', models.TextField(verbose_name='Описание')),
                ('download_link', models.CharField(max_length=128, verbose_name='Ссылка для скачивания')),
                ('game_icon', models.BinaryField(verbose_name='Иконка')),
            ],
        ),
    ]
