# Generated by Django 4.1.5 on 2023-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_icon',
            field=models.ImageField(upload_to='photos', verbose_name='Иконка'),
        ),
    ]
