# Generated by Django 4.1.5 on 2023-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_games_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_icon',
            field=models.ImageField(upload_to='photos/%Y/%m/', verbose_name='Иконка'),
        ),
    ]
